language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - # default environment without variables
  - COMPOSER_DEPENDENCIES_OPTIONS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer update --no-interaction --prefer-source $COMPOSER_DEPENDENCIES_OPTIONS

script:
  - bin/parallel-lint -e php,phpt src tests
  - bin/phpcs -sp --standard=vendor/nella/coding-standard/Nella/ruleset.xml src tests
  - bin/tester -s -p php -c tests/php.ini tests --coverage build/clover.xml --coverage-src src

after_success:
  - composer require symfony/yaml 2.6 satooshi/php-coveralls dev-master#2fbf803 --no-interaction --prefer-source --no-progress --ignore-platform-reqs || true
  - bin/coveralls --verbose --config build/coveralls.yml || true
